name: yolo-video-detection-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.20.0
  - cython~=3.0.0
  - setuptools>=63.0
  - wheel>=0.40
  
  # Development tools
  - pytest
  - flake8
  - black
  - isort
  
  # PyTorch GPU version with CUDA 11.8
  - pytorch-cuda=11.8
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  
  # OpenCV (conda-forge version)
  - opencv
  
  # Additional scientific packages
  - scipy
  - matplotlib
  - pandas
  
  # CUDA toolkit components (optional, if not using system CUDA)
  - cudatoolkit=11.8
  
  - pip:
    # Project-specific requirements
    - pyyaml
    - ultralytics~=8.0.114
    - av~=10.0.0
    - onnxsim~=0.4.33
    - onnx~=1.14.0
    - onnxruntime-gpu>=1.11.0  # GPU version of onnxruntime
    
    # Install the local package in development mode
    - -e .