version: 1
disable_existing_loggers: false
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  detailed:
    format: '%(asctime)s - %(levelname)s - %(threadName)s:%(processName)s - %(module)s:%(funcName)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  minimal:
    format: '%(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO  # Changed from DEBUG to INFO
    formatter: minimal  # Changed to minimal format
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: yolo_server.log
    mode: a

loggers:
  server_processing:
    level: INFO  # Changed from DEBUG to INFO
    handlers: [console, file]
    propagate: no

  root:
    level: WARNING  # Changed from INFO to WARNING for even less noise
    handlers: [console, file]